//created on: Jan 3, 2017
package price

//list any import classes here.
import pojo.UserInfo


//declare any global variables here
dialect "java"



rule "Your First Rule"

    when
        item : UserInfo (tipRizika == UserInfo.TipRizika.SLAB, 
        				destinacija == UserInfo.Destinacija.SRBIJA)
    then
        double pk1 = 150,00;
        double pk2 = 200,00;
        double pk3 = 250,00;
        
        double kR = item.getKoefRizika();
        double kO = item.getKoefOdraslih();
        double kD = item.getKoefDece();
        double kDst = item.getKoefDestinacije();
        int brO = item.getBrOdraslih();
        int brD = item.getBrDece();
        int brDn = item.getBrDana();
        
        item.setCenaPaketa1(pk1*kR*brO*kO*brD*kD*kDst*brDn);
        item.setCenaPaketa2(pk2*kR*brO*kO*brD*kD*kDst*brDn);
        item.setCenaPaketa3(pk3*kR*brO*kO*brD*kD*kDst*brDn);

end

rule "Your Second Rule"
    //include attributes such as "salience" here...
    when
        //conditions
    then
        //actions

end
